name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"
      - name: Install pipenv
        run: pip install --upgrade pipenv wheel
      - name: Install python dependencies
        run: pipenv install --dev --deploy
      - name: Install flit dependencies
        run: pipenv run flit install --symlink
      - name: Test
        run: bash scripts/tests.sh
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pipenv run coveralls
